### ISSUE TITLE
branch protection rule for master?

### ISSUE THREAD

**Issue by kkmann** [pharmaR/riskmetric#11]
I think it would be a good idea to have a mandatory review system for changes to master in place. Makes code changes more transparent to others and improves quality in the long run. Probably one reviewer would be enough. Passing the CI tests should also be mandatory for master (once we get them going again ;))

I.e. I am suggesting to use the formal branch protection system of GitHub.

**Comment by elong0527** [comment]
Totally agree! It is great to see all these progress.  

Sorry for the dealy, I am on vacation this week. I will handle them within this week.
