### ISSUE TITLE
Introduce `pkg_metric_na` subclass to differentiate not-applicable assessments

### ISSUE THREAD

**Issue by dgkf** [pharmaR/riskmetric#118]
The warnings generated by assessments which may not be applicable to certain `pkg_ref` subclasses seem to be generating a lot of confusion. Rightfully so. The warnings signal quite a bit of internal jargon and give no indication that they are expected behavior.

As mentioned in the discussion in #114 with @mpadge, and in a few emails I've received from users, these warnings seem to be missing the mark in terms of user reaction, so something isn't being communicated properly.

To mitigate this, I suggest adding a `pkg_metric_na` subclass similar to our existing `pkg_metric_error`. This will differentiate metrics which are explicitly not applicable from those that have not yet been implemented (maybe we should even have a `pkg_metric_todo`?). We could then choose how to handle these separately from errors and hopefully provide more meaningful output to the user.

Open for feedback on the design here, but I think it's worth experimenting with.

**Comment by andyofsmeg** [comment]
As per email thread I just want to highlight that these changes are required for the associated app to function as expected.  In particular I believe the app expects a `pkg_metric_na` class.
