### ISSUE TITLE
Discussion of the alignment with the shiny app

### ISSUE THREAD

**Issue by elong0527** [pharmaR/riskmetric#120]

**Comment by elong0527** [comment]
*  waiting time for the app 
    - code coverage report CI/CD
     - internal situation (how to link codecov commit information with package version?)
     - public situation
*  #118 
*  how to maintain the app after initial release
*  build a database to host the results?

**Comment by andyofsmeg** [comment]
Can I add #129 as well please?

**Comment by elong0527** [comment]
Transition date: Aug 1st
@marlycormar  would provide feedbacks to improve riskmetric package based on the need for shinyapp.

**Comment by elong0527** [comment]
Team discussed and suggest to separate the package and shiny app:

# Combined shiny app and package:

## Con: 

1. dependency will increased for the shiny app
2. code base for existing shiny app folder structure is not an R package

## Pro:

**Comment by elong0527** [comment]
* explore how to add a hook to RSPM
  - renvr, packrat? 
  - pending update from a meeting with Phil, Marly and Eli.

**Comment by elong0527** [comment]
Happy to revisit after more opinion collected.
