### ISSUE TITLE
Update assess_* functions that have the assess_news_current description

### ISSUE THREAD

**Issue by ndelcamp** [pharmaR/riskmetric#122]
Small documentation updates are needed to a couple of the `assess_*` functions. `assess_license`, and `assess_covr_coverage` have the description "Assess a package for an up-to-date NEWS file".

**Comment by dgkf** [comment]
Good catch! I'll quickly update these. Thanks for lending your keen eye!

**Comment by dgkf** [comment]
Resolved in #123
