### ISSUE TITLE
Include weight for downloads_1yr in .risk_weights 

### ISSUE THREAD

**Issue by ndelcamp** [pharmaR/riskmetric#124]
The downloads_1yr metric is not included in the risk calculation because it is not included in `.risk_weights`.

**Comment by dgkf** [comment]
Another good find. This vector often gets overlooked as new metrics get added. 

I think we need to consider a better mechanism of setting defaults than building the vector manually. Perhaps a function which defaults to a weights of `1` for every assessment, but which accepts named parameters to overwrite this default would be more flexible and maintainable.

**Comment by marlycormar** [comment]
Hi @dgkf and @elong0527, we should be able to close this issue now that PR #135 has been merged.
