### ISSUE TITLE
metric for R CMD check 

### ISSUE THREAD

**Issue by elong0527** [pharmaR/riskmetric#131]
capture the output of R CMD check 

option 1: run the command from local 

option 2: parse information in CRAN e.g. https://cran.r-project.org/web/checks/check_results_ggplot2.html

**Comment by mpadge** [comment]
3. Use [`foghorn`](https://github.com/fmichonneau/foghorn) to parse the CRAN info
4. Use [`cchecks`](https://github.com/ropenscilabs/cchecks) to access the historical checks database of [`cranchecks.info`](https://cranchecks.info).

**Comment by elong0527** [comment]
CI/CD failed, will check the local build.
