### ISSUE TITLE
Improving error messages explanation

### ISSUE THREAD

**Issue by marlycormar** [pharmaR/riskmetric#149]
When a package doesn't contain some of the metrics we are assessing, e.g., NEWS, bug reports, etc., the user will get warnings/errors which do not state which metrics are missing but rather output a generic error message. Should we improve the warning/error messages shown?

To see this issue in action, we can use `riskmetric` on the `extratests` package. This package lacks some of the metrics we test. For example, the following code

```r
library(dplyr)
library(riskmetric)

pkg_ref("extratests") %>%
  pkg_assess() %>%
  pkg_score() 
```

produces this list of warnings

```
Warning messages:
1: In error_handler(x, ...) :
  no available scoring algorithm for metric of class "pkg_metric_error", returning default score of 0.
2: In error_handler(x, ...) :
  no available scoring algorithm for metric of class "pkg_metric_error", returning default score of 0.
3: In error_handler(x, ...) :
  no available scoring algorithm for metric of class "pkg_metric_error", returning default score of 0.
4: In error_handler(x, ...) :
  no available scoring algorithm for metric of class "pkg_metric_error", returning default score of 0.
5: In error_handler(x, ...) :
  no available scoring algorithm for metric of class "pkg_metric_error", returning default score of 0.
6: In error_handler(x, ...) :
  no available scoring algorithm for metric of class "pkg_metric_error", returning default score of 0.
7: In error_handler(x, ...) :
  no available scoring algorithm for metric of class "pkg_metric_error", returning default score of 0.
8: In error_handler(x, ...) :
  no available scoring algorithm for metric of class "pkg_metric_error", returning default score of 0.
9: In error_handler(x, ...) :
  no available scoring algorithm for metric of class "pkg_metric_error", returning default score of 0.
10: In error_handler(x, ...) :
  no available scoring algorithm for metric of class "pkg_metric_error", returning default score of 0.
```

from which you cannot conclude that the NEWS file for example is missing.

**Comment by elong0527** [comment]
tibble package : need to put tibble in import.

**Comment by dgkf** [comment]
Thanks @marlycormar - when I run this code, we get an object of `pkg_missing` (returned by `pkg_ref` when we can't find a source for the package locally, on CRAN or on Bioconductor). I'm not familiar with this package and a quick search isn't turning anything up.

In any event, this error message isn't informative and we might want to handle `pkg_missing` subclasses within `pkg_assess()` and `pkg_score()` as a special case.

**Comment by dgkf** [comment]
Since this was an issue with the creation of the pkg_ref("extratests") example, we're instead going to open a separate issue for communicating pkg_ref missingness.
