### ISSUE TITLE
link back to https://www.pharmar.org/packages/?

### ISSUE THREAD

**Issue by kkmann** [pharmaR/riskmetric#15]
I feel there should be a link back to https://www.pharmar.org/packages/ in the README.md and maybe a short paragraph on the PSI SIG ('who are we?')? - not quite feeling that competent there yet ;)

**Comment by elong0527** [comment]
yeah, maybe @andyofsmeg  could help on this. Would you want to close this one and open an issue in the https://github.com/pharmaR/pharmaR.github.io

**Comment by kkmann** [comment]
not much activity there + it concerns this repo. maybe the best forum is our slack? let's leave this open here and maybe discuss it on the next call?
