### ISSUE TITLE
Repo maintenance: Clearing out stale branches

### ISSUE THREAD

**Issue by dgkf** [pharmaR/riskmetric#155]
We've got quite a few branches at the moment, most of which are defunct or have been pulled into master but were not deleted. I propose at our next sprint meeting we go through our old branches and clear out the ones that aren't under active development. I suspect that the vast majority of dev/ branches can be removed, but let's confirm on a call before clearing things out. 

Hopefully this helps to keep the project a bit more organized and focused.

**Comment by emilliman5** [comment]
Looks like this task has been complete, only 7 branches in the repo currently
