### ISSUE TITLE
Cohort Metric for Namespace Conflicts

### ISSUE THREAD

**Issue by elimillera** [pharmaR/riskmetric#176]
From the R in Pharma validation workshop:

Loading in packages with conflicting function names can cause a number of issues in your package/environment. A good proxy for incompatible packages would be the number of conflicts that arise between namespaces. By using `getNamespaceExports()` on a call to a cohort or library and sum the number of overlaps.

The example used at the workshop was `dplyr` and `plyr`
Here's an example of how these scores could be calculated.
```
> counts <- c(getNamespaceExports("plyr"), getNamespaceExports("dplyr")) %>%
+     plyr::count() %>%
+     dplyr::filter(freq > 1)
          x freq
1   arrange    2
2     count    2
3      desc    2
4  failwith    2
5        id    2
6    mutate    2
7    rename    2
8 summarise    2
9 summarize    2

nrow(counts)
[1] 9
```

**Comment by elong0527** [comment]
Depends on #174
