### ISSUE TITLE
tally_coverage

### ISSUE THREAD

**Issue by elong0527** [pharmaR/riskmetric#183]
The `by` options seems not allow `function`

https://www.rdocumentation.org/packages/covr/versions/3.5.1/topics/tally_coverage

https://github.com/pharmaR/riskmetric/blob/4621cc7705838746917a9684171f94639cc4a198/R/pkg_ref_cache_function_coverage.R#L12

**Comment by dgkf** [comment]
thanks for highlighting this - I believe it should be "expression"
