### ISSUE TITLE
convert from `read_html` to `httr::content(httr::GET())` for unit testing

### ISSUE THREAD

**Issue by emilliman5** [pharmaR/riskmetric#186]
We can pull this in before we look toward testing it, but eventually we'll need to replace `read_html` with `httr::content(httr:GET(...))` in order to intercept web requests with `webmockr`.

_Originally posted by @dgkf in https://github.com/pharmaR/riskmetric/pull/170#discussion_r511636858_

**Comment by mpadge** [comment]
Just a note in case you folk missed it, but rOpenSci's reference book on http testing has gone through a pretty solid update, detailed in [this blog post](https://ropensci.org/blog/2021/01/26/http-testing-book/).

**Comment by emilliman5** [comment]
closed by #245
