### ISSUE TITLE
Separate 'scoring' from `get_*` to decouple metadata gathering from assessment

### ISSUE THREAD

**Issue by dgkf** [pharmaR/riskmetric#19]
_inspired by conversation in #17, related to #18 conversation with @kkmann & @elong0527_

---

Similar to using S3 for the `get_*` function dispatch, I think that the scoring function should also be extensible to allow organizations to customize the way that package metadata is summarized, and that each `get_*` (or alternatively named) function should return a standardized S3 object which can be extended for scoring overloading.

A trivial example may be to have `get_has_NEWS()` which may return an S3 object such as 

```r
structure(TRUE, class = c("has_NEWS_metadata", "pkg_metadata")
```

which is then passed to `score.has_NEWS_metadata()`

A more meaningful example might be for `get_public_contributions(x)` which might return:

```r
structure(data.frame(
  name = c("dgkf", "kkmann", "elong0527"), 
  line_edits = c(23, 42, 777),
  last_edit = c("2019-01-02", "2019-02-03", "2019-03-04")), 
  class = c("public_contributions_metadata", "pkg_metadata"))
```

where `score.public_contributions_metadata(x)` evaluates to just `nrow(x) > 1`, but a more sophisticated way to evaluate risk might be to look at the distribution of lines contributed by contributors as a proxy for distributed familiarity of the package code base.

**Comment by kkmann** [comment]
Might be a bit over the top for where we are now - extensibility is certainly great but I'd rather start with something much simpler and extend it later. Just getting the basics right already seems pretty daunting to me ...
