### ISSUE TITLE
A metric of how many Reverse dependencies a package has

### ISSUE THREAD

**Issue by elong0527** [pharmaR/riskmetric#193]

**Comment by emilliman5** [comment]
There are at least two types of metrics that can be born out of an assessment of a package's reverse dependencies:
1) as a measure of popularity/community engagement, e.g. there are many packages that extend ggplot with various pre-built layers/geoms/plots

2) In a cohort of packages, e.g. a user's current library, the number of reverse dependencies would signal it's importance in the dependency tree. e.g. if there is an error/bug in ggplot, that error would potentially permeate throughout all packages that depend on it.

**Comment by emilliman5** [comment]
Partially fullfilled with #219, closing for now
