### ISSUE TITLE
Enhancement of package source 

### ISSUE THREAD

**Issue by elong0527** [pharmaR/riskmetric#196]
From #175 

I would prefer to have more direct and rigid mechanisms for creating specific classes (pkg_source("<source directory>"), pkg_remote("<remote url>")) and then move the current pkg_ref functionality into a convenience function whose name indicates that it is doing some type conversion (as_pkg_ref("arbitrary character value")), possibly with some arguments that can limit the scope of viable sources.

One thing that really irks me is that pkg_ref is not type-stable, returning either a pkg_ref or list_of_pkg_ref class object depending on the length of the input character vector. It would be nice to make this more stable as well, either always returning a list or breaking out the flavor that can accommodate a vector.

In the spirit of putting a design out there for critique, here are some ideas for some tighter constructors:

```
# rigid constructors always return a single pkg_ref subclass object
pkg_source("file path")
pkg_remote("url", base_url = "optional base url")
pkg_cran("package name") # wrapper around pkg_remote with base_url default
pkg_bioc("package name") # wrapper around pkg_remote with base_url default
pkg_install("absolute or relative file path", lib_loc = "optional relative path origin") 
```
```
# attempt to parse a character for the appropriate pkg_ref, similar to pkg_ref now
find_pkg_ref("arbitrary string") # or 
as_pkg_ref("arbitrary string")
```

```
# to concretely build a package cohort
src_paths <- c("dev/pkg1", "dev/pkg2")
lapply(src_paths, pkg_source) # note, will not be a "list_of_pkg_ref", but rather a "list"
```

```
# finally, as we're starting to think about cohorts more, I might suggest
pkg_library("library location") # returns a pkg_cohort object. in this case, a list of pkg_install 
pkg_cohort() # no arguments, just instantiates a structure around an empty list
as_pkg_cohort([list of pkg refs]) 
```

**Comment by elimillera** [comment]
@elong0527 I like all of these. I can get started on that now. I am a bit concerned that this is a breaking change to a major function. Are you thinking we just depreciate pkg_ref and give a link to the new process?

**Comment by elong0527** [comment]
I would defer to @dgkf. This is the original comments left by him.

**Comment by elimillera** [comment]
Per meeting `pkg_ref` wouldn't be depreciated but would be used to determine the source
