### ISSUE TITLE
Risk Assessment app alignment with riskmetric

### ISSUE THREAD

**Issue by marlycormar** [pharmaR/riskmetric#216]
Hi team, since `riskmetric` is already in CRAN, I think the `risk assessment app` would benefit from the team's feedback. What is the best way to get feedback from the team? Would you like me to give a quick demo on the next `riskmetric` meeting?

Potential discussion topics:
- How to better align the app with the package?
- There are many features that can be added to the app, but among those, which one would be beneficial for current or even future features of `riskmetric`?
- How to increase visibility of the app?

@dgkf, @elong0527, @emilliman5

**Comment by dgkf** [comment]
> There are many features that can be added to the app, but among those, which one would be beneficial for current or even future features of riskmetric?

@marlycormar Would it be possible to itemize these for the discussion, or is it too varied? 

> How to increase visibility of the app?

Do we have a deployment available? Perhaps we could start by getting a live demo up on RStudio cloud or alternative?
