### ISSUE TITLE
riskmetric is archived on CRAN

### ISSUE THREAD

**Issue by llrs** [pharmaR/riskmetric#218]
I wanted to look at the package but I found it is no longer on [CRAN](https://cran.r-project.org/package=riskmetric):

> Package ‘riskmetric’ was removed from the CRAN repository.
> 
> Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/riskmetric).
> 
> Archived on 2021-08-17 as repeated check problems were not corrected in time.
> 
> A summary of the most recent check results can be obtained from the [check results archive](https://cran-archive.r-project.org/web/checks/2021/2021-08-17_check_results_riskmetric.html).
> 
> Please use the canonical form [https://CRAN.R-project.org/package=riskmetric](https://CRAN.R-project.org/package=riskmetric) to link to this page.
> 

The only check I found failing is on r-devel-fedora-gcc (copying it here as I don't know how long these checks archives stay):

<details>
<summary>Check Details</summary>

> Version: 0.1.1
> Check: tests
> Result: ERROR
>      Running ‘testthat.R’ [150s/168s]
>     Running the tests in ‘tests/testthat.R’ failed.
>     Complete output:
>      > library(testthat)
>      > library(riskmetric)
>      >
>      > options(repos = "fake-cran.fake-r-project.org")
>      >
>      > test_check("riskmetric")
>      ══ Skipped tests ═══════════════════════════════════════════════════════════════
>      • snapshots appear to be failing due to random order of pkg_ref fields (3)
>     
>      ══ Failed tests ════════════════════════════════════════════════════════════════
>      ── Failure (test_pkg_ref.R:31:3): pkg_ref infers source when not explicitly provided ──
>      `ref3` has class 'pkg_install'/'pkg_ref'/'environment', not 'pkg_bioc_remote'/'pkg_remote'/'pkg_ref'/'environment'.
>      ── Failure (test_pkg_ref.R:32:3): pkg_ref infers source when not explicitly provided ──
>      ref3$source (`actual`) not equal to "pkg_bioc_remote" (`expected`).
>     
>      `actual`: "pkg_install"
>      `expected`: "pkg_bioc_remote"
>     
>      [ FAIL 2 | WARN 0 | SKIP 3 | PASS 45 ]
>      Error: Test failures
>      Execution halted
> Flavor: r-devel-linux-x86_64-fedora-gcc

</details>

Not sure if you were aware, but is there a plan to submit the package to CRAN again?
Edit: I just realize that there was a [recent release](https://github.com/pharmaR/riskmetric/pull/217) on 2021-07-29, which doesn't seem to have fixed all the errors.

**Comment by dgkf** [comment]
Thank you for bringing this to our attention @llrs!

We'll make this a priority and will plan to resubmit.

**Comment by daroczig** [comment]
Not sure if you have considered not running the unit tests on CRAN, but keeping those to GH Actions.

**Comment by elimillera** [comment]
I've been looking for some documentation about what the CRAN machine looks like and I'm not coming up with much. I think @emilliman5 idea of explicitly stating what source we looking for is the best option. I think hoping that the CRAN machine doesn't have a package is not the most stable approach.

I'll go ahead and update and send a PR in

**Comment by dgkf** [comment]
We can also mock the installed packages for this test to guarantee that the package isn't recognized as "installed", even if it is available on the testing machine. I've been using `mockery::stub` a lot for this recently. This could be thrown within a `test_that()` block to only stub the function within that context.

```
mockery::stub(pkg_ref, "installed.packages", function(...) {
  inst <- installed.packages()
  inst[which(!rownames(inst) %in% "limma"),]
})
```

(code is untested, but hopefully the intention is clear)
