### ISSUE TITLE
Minor bug when summarizing risk metric scores

### ISSUE THREAD

**Issue by stephannie-s** [pharmaR/riskmetric#222]
With riskmetric v0.1.1, I'm getting the following error when I try to get the risk metric scores for one package:
`res <- pkg_ref(c("MatchIt")) %>%
     pkg_assess() %>%
     pkg_score() %>%
     dplyr::mutate(risk = riskmetric::summarize_scores(.))`
`Error in UseMethod("mutate") : 
  no applicable method for 'mutate' applied to an object of class "list"`

But when I add an additional package, the error is resolved and I'm able to get the summary scores:
`res <- pkg_ref(c("MatchIt", "ggplot2")) %>%
     pkg_assess() %>%
     pkg_score() %>%
     dplyr::mutate(risk = riskmetric::summarize_scores(.))`

**Comment by dgkf** [comment]
Thanks @stephannie-s. This is a good call-out - one of the shortcomings of our flexible `pkg_ref` function is that it will try to be "smart" about what return type works best for you. 

If just one package is passed, it returns a list, but if multiple packages are passed, it returns a `tibble`. The tradeoff is that it can be unstable for situations where you want the same code to work in both cases.

To make sure that you get a `tibble` in both cases, you can pipe the result of `pkg_ref` to `as_tibble()` before proceeding with `pkg_assess()` - this will convert the list to the tibble and allow you to proceed.

Can you try this to see if it resolves the problem?

```r
res <- pkg_ref(c("MatchIt")) %>% 
  dplyr::as_tibble() %>%
  pkg_assess() %>% 
  pkg_score() %>% 
  dplyr::mutate(risk = riskmetric::summarize_scores(.))
```

**Comment by stephannie-s** [comment]
Perfect! I no longer saw the error message after using your suggested code. Thank you so much!
