### ISSUE TITLE
riskmetric survey shiny app

### ISSUE THREAD

**Issue by elong0527** [pharmaR/riskmetric#235]
- re-deploy the app
- a blog post / email to the R validation hub

**Comment by emilliman5** [comment]
I have updated the package list for the riskmetric survey app, I also generated a short description of the [selection process](https://emilliman5.github.io/Riskmetric_survey/Package_selection.html). A table of the packages selected is at the end of the document. Please have a look and let me know (here on slack or via PR) if you think we should add some more packages or specific packages to the list.

**Comment by elong0527** [comment]
an email has been sent to the enactive committee.

Below is the information.

The [RValidationHub](https://www.pharmar.org/white-paper/) has proposed 4 criteria for the assessment of package risk:
Purpose
Maintenance Good Practices (Software Dev Life Cycle)
Community Usage
Testing
The [riskmetric](https://pharmar.github.io/riskmetric/) package and [risk assessment app ](https://github.com/pharmaR/risk_assessment)are tools that can be used to assess package risk.
The [riskmetric](https://pharmar.github.io/riskmetric/) team aims to empirically derive weights (importance factors) for summarizing package metrics into a risk score, using a short survey located here: 
https://rinpharma.shinyapps.io/Riskmetric-Survey/ or https://bit.ly/3myyzif

**Comment by kimjj93** [comment]
It looks like https://rinpharma.shinyapps.io/Riskmetric-Survey/ is down?

**Comment by emilliman5** [comment]
> It looks like https://rinpharma.shinyapps.io/Riskmetric-Survey/ is down?

Yes, we are working to get it resolved.

**Comment by emilliman5** [comment]
The App is redeployed and working
