### ISSUE TITLE
riskmetric score is no longer in [0, 1] with riskmetric v0.1.2?

### ISSUE THREAD

**Issue by timtreis** [pharmaR/riskmetric#246]
Hey there!

Over at https://github.com/openpharma/visR we had implemented a badge for our riskmetric score. However, while testing I just noticed that our README now builds incorrectly because the score is suddenly negative? I am able to reproduce the negative score too.

Has the definition of the metric changed? Accordings to the docs it shouldn't be negative -> https://pharmar.github.io/riskmetric/reference/pkg_score.html

![image](https://user-images.githubusercontent.com/12818242/155973923-5fc0a225-ec00-4a9a-a7a1-35e67644abdb.png)

**Comment by timtreis** [comment]
Just confirmed that with riskmetric v0.1.1 it gives an expected score in [0, 1]

![image](https://user-images.githubusercontent.com/12818242/155976353-6575d789-38a1-4345-928e-db78e7eb2c65.png)

**Comment by emilliman5** [comment]
This will issue is fixed by PR #242
