### ISSUE TITLE
Increment `riskmetric` version on `master`

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/riskmetric#270]
Hi all,

I was using `riskmetric` on CRAN and encountered a bug. I checked GitHub to see if there was a fix, but `master` was tagged with the same version number as CRAN (v0.1.2) so I assumed the code was the same. Thus, didn't re-install from Github. However, @borgmaan noticed there had been a lot of changes on `master` since the last CRAN release (here is the [diff](https://github.com/pharmaR/riskmetric/compare/v0.1.2...master#diff-77c7e32166868f17a6d667a357b389e34b463d8d6597496e873cd86294399d49R59)), including [the fix](https://github.com/pharmaR/riskmetric/commit/7b95959237096eba814cacecce8e4de9396e3c94) to the bug I encountered. Yay!

Is there a reason the package version on `master` hasn't been incremented so users know that `riskmetric` on GitHub is ahead of CRAN? Probably boosting to v0.1.3 via `usethis::use_version("patch")`  and updating the `NEWS.md` file would be sufficient.

Thanks!

**Comment by elimillera** [comment]
Hey all,

We seem to be getting some errors with the man pages when I run R CMD check and send this to RHub. I can look into this but we likely want to update our pipelines going forward so they catch this as well.

**Comment by elimillera** [comment]
Errors are similar to:
```
Warning: [assess_covr_coverage.R:3] @eval failed to evaluate
Caused by error in `roxygen_assess_family()`:
! All assess_* functions must have a corresponding score.* method implemented.

To remove build errors, ensure that the following functions are implemented:

  assess_covr_coverage()
  metric_score.pkg_metric_covr_coverage()
Warning in roxygen_score_family("covr_coverage", dontrun = TRUE) :
  Error when generating documentation for covr_coverage. Associated scoring function `metric_score.pkg_metric_covr_coverage` was not found in the `riskmetric` package. Please provide one to complete documentation.
```

**Comment by elimillera** [comment]
Removing the if condition here: https://github.com/pharmaR/riskmetric/blob/527c07a5fbd696e92feacb80c8e438a01c79a922/R/pkg_assess.R#L34

@AARON-CLARK @emilliman5  Did we want to remove this and update the docs after a patch release, or did we want to add these docs now?

**Comment by emilliman5** [comment]
That's an odd error to be getting, since assess_covr_coverage has been implemented for quite some time and the metric_score is implemented. I will take a look before our sprint on Wed and report back. But I agree, we need a build pipeline that can prevent this annoying documentation errors.

**Comment by elimillera** [comment]
New version is on its way to CRAN!
