### ISSUE TITLE
`assess_export_help()` for package source code

### ISSUE THREAD

**Issue by seth127** [pharmaR/riskmetric#284]
Hello. First of all, this is great project! I've watched several webinars related to `riskmetric` and the Risk Assessment app and I've learned a lot from all of them.

My specific question is about the `assess_export_help()` function. It looks to me like it is [implemented for installed packages](https://github.com/pharmaR/riskmetric/blob/4bc6f955eee0860d14d05656615917f5cd10d678/R/assess_export_help.R#L33-L42), but [_not_ for source code directories](https://github.com/pharmaR/riskmetric/blob/4bc6f955eee0860d14d05656615917f5cd10d678/R/assess_export_help.R#L26-L29). Is that correct? If so, is there a reason for that? Are you planning to add support for source code as well?

I ask because I am interested in using `riskmetric` and this seems like a very useful metric, but the pipeline I'm planning to use it in will have easy access to the package source code, but _not_ the installed package. 

Thanks!

**Comment by emilliman5** [comment]
We are glad you are enjoying this project. You are correct, the `assess_export_help` is only implemented for pkg_refs of installed packages. At first glance, it looks like refs of type `pkg_install` allow us some convenience by fully expanding any shorthand in the NAMESPACE, among other things.   I will take a look to assess the feasibility of implementing this assessment for pkg_refs of source directories.

**Comment by seth127** [comment]
Thanks very much! And also for the quick response. And let me know if you would be interested in taking a pull request, if you like the idea but don't have the time for it in the near future.

**Comment by seth127** [comment]
Thanks for getting to this so quickly!

**Comment by seth127** [comment]
Hello. I saw this was merged last Spring, and the version in DESCRIPTION was updated to `0.2.2` not long after, but I don't see a tagged release with that update. Is this officially released at this point? If not, do you have any plans for a release? Thanks!
