### ISSUE TITLE
S3 environment + extract operator overloading vs. R6 + methods

### ISSUE THREAD

**Issue by dgkf** [pharmaR/riskmetric#31]
@kieranjmartin in #30 rightfully questioned the possibly overengineered nature of the S3 implementation for the package references.

The S3-style package reference objects evolved out of a fairly minimalist design which slowly grew in complexity when we tried to put on some guardrails to prevent re-deriving intensive metadata or derived values. 

In practice, it's beginning to resemble an R6 class. Would it be better to rewrite these pieces in R6? Would an R6 design be more contributor-friendly since it's familiar, or more challenging because it would require more familiarity with the class construction?

Admittedly I don't have all that much experience with R6, so I don't have a strong sense for the pros and cons.

**Comment by kieranjmartin** [comment]
So this is somewhat up to an individual preference, but somewhere in the documentation of ggplot it mentions that ggplot essentially invented its own object orientated language and does not recommend anyone does so in future.

While r6 is new it has the advantages of being very light weight and easy to use. The accesor style for methods and objects is to use $ which feels natural to me, and feels quite pythonesque too. I think that it's not super hard for a user to make use of, and you can always make wrapper functions which are just applications of the methods if you want to be super friendly to beginners.

The big downside of r6 at the moment for me is that roxygen does not handle it, and all solutions for documentation tend to be kludges. My favourite current version is building documentation files for methods via those wrapper functions I mentioned above, then linking to them in the class documentation, but it's not perfect.

I get the impression that updating roxygen to handle r6 is in the pipeline, but could be a very long time

**Comment by elong0527** [comment]
As suggested by @dgkf, I would hope to keep on the S3 method in current stage. 

If we move to R6, I expect many users need to learn R6 before contributing. (I will also be one of them). 

I would also hope we could limit package dependencies for this project.
