### ISSUE TITLE
package name change

### ISSUE THREAD

**Issue by dgkf** [pharmaR/riskmetric#39]
In our group meeting on 2019/09/17, Patrice K. mentioned that "RiskMetrics" conflicts with a [variance model produced by J.P. Morgan in the 90s](https://en.wikipedia.org/wiki/RiskMetrics). 

I assume the name conflict is probably not worth any potential legal issues and ambiguity (especially in a statistical programming language where someone may be looking for a package to run these models).

Please let me know how people feel about the naming conflict, and feel free to make suggestions if you've got one.

**Comment by elong0527** [comment]
I agree with your evaluation and OK to keep the package name as is.

**Comment by emdserono** [comment]
What about `Rmetric`?

Output from `available("Rmetric")`

```
-- Rmetric ---------------------------------------------------------------------
Name valid: ✔
Available on CRAN: ✔ 
Available on Bioconductor: ✔
Available on GitHub:  ✔ 
Abbreviations: http://www.abbreviations.com/metric
Wikipedia: https://en.wikipedia.org/wiki/metric
Wiktionary: https://en.wiktionary.org/wiki/metric
Urban Dictionary:
  a) [the metric system]; a system used to  measure/[weigh] things.  b) a canadian [indie band].
  http://metric.urbanup.com/1340086
Sentiment:???
Abbreviations: http://www.abbreviations.com/Rmetric
Wikipedia: https://en.wikipedia.org/wiki/Rmetric
Wiktionary: https://en.wiktionary.org/wiki/Rmetric
Urban Dictionary:
  Not found.
Sentiment:???
```

**Comment by elong0527** [comment]
Either `Rmetric` or `riskmetric` is fine for me. If we use `Rmetric`, could we use lower cases for all (i.e. `rmetric`)?

**Comment by elong0527** [comment]
agreed to keep it as is.
