### ISSUE TITLE
Metric for gauging suitability of a software license

### ISSUE THREAD

**Issue by dgkf** [pharmaR/riskmetric#53]
This one probably requires a pretty candid conversation across the industry and a bit of health authority input.

Any guidelines that people have been using in the industry would be super helpful! If anyone doesn't feel comfortable making a claim to a license policy, perhaps there are public open source guidelines we can defer to that would let us begin to get our heads around suitable licenses.

**Comment by matthiazzz** [comment]
**This post is by no means any legal advice nor binding in any way.**

The R Foundation clarifies if R and R add-on packages may be used commercially [here](https://cran.r-project.org/doc/FAQ/R-FAQ.html#Can-I-use-R-for-commercial-purposes_003f). They state that most add-on packages explicitly allow commercial use. Yet, they also state that they cannot provide legal advice... 

To be more precise: a database with licences used at CRAN can be accessed via [this link](https://svn.r-project.org/R/trunk/share/licenses/license.db).

R code to grab and store all of the licences is below (not beautiful, but works). Note that they do provide a entry "restricts use" but I was unable to find a clear statement what exactly that means. 


**R Code to parse the licence.db file**
`# link to licencse file from R
source_file <- "https://svn.r-project.org/R/trunk/share/licenses/license.db"

# read them in
licences <- read.delim(source_file, header = FALSE)

res <- data.frame(Entry1=NaN, Entry2=NaN)
for (i in 1:nrow(licences)) {
  value<-regmatches(as.character(licences[i,1]), regexpr("*: ", as.character(licences[i,1])), invert = TRUE) 

# split after first colon
  res[i,]<-value[[1]]
}
res_final <- data.frame(
  "Name"=NaN, "Abbrev"=NaN,"Version"=NaN,"SSS"=NaN,"OSI"=NaN,"FSF"=NaN,"File"=NaN,"URL"=NaN,"FOSS"=NaN,
  "Extensible"=NaN,"Restricts_use"=NaN,"Note"=NaN)

k=0
for (i in 1:nrow(res)) {
  if (res[i,1]=="Name") {
    k<-k+1
    if (k>1) res_final<-rbind(res_final, "")
    res_final$Name[k] <- as.character(res[i,2])
  }
  if (res[i,1]=="Abbrev")     {res_final$Abbrev[k] <- as.character(res[i,2])}
  if (res[i,1]=="Version")    {res_final$Version[k] <- as.character(res[i,2])}
  if (res[i,1]=="SSS")        {res_final$SSS[k] <- as.character(res[i,2])}
  if (res[i,1]=="OSI")        {res_final$OSI[k] <- as.character(res[i,2])}
  if (res[i,1]=="FSF")        {res_final$FSF[k] <- as.character(res[i,2])}
  if (res[i,1]=="File")       {res_final$File[k] <- as.character(res[i,2])}
  if (res[i,1]=="URL")        {res_final$URL[k] <- as.character(res[i,2])}
  if (res[i,1]=="FOSS")       {res_final$FOSS[k] <- as.character(res[i,2])}
  if (res[i,1]=="Extensible")     {res_final$Extensible[k] <- as.character(res[i,2])}
  if (res[i,1]=="Restricts_use")        {res_final$Restricts_use[k] <- as.character(res[i,2])}
  if (res[i,1]=="Note")        {res_final$Note[k] <- as.character(res[i,2])}
}

write.csv2(res_final, "out.csv")
`

**Comment by matthiazzz** [comment]
Essentially, the following licencses seem to restrict commercial use:

- ACM Software License Agreement
- Creative Commons Attribution-NonCommercial 3.0 Unported License
- Creative Commons Attribution-NonCommercial 4.0 International License
- Creative Commons Attribution-NonCommercial-NoDerivs 3.0 United States License
- Creative Commons Attribution-NonCommercial-NoDerivs 4.0 International License
- Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License
- Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License

**Comment by dgkf** [comment]
Thanks for kicking off this discussion @matthiazzz. This looks like a great start, and allows us to provide a licensing recommendation based on the R project's database, which I much prefer to the alternative of trying to decide on which licenses we may endorse by default. 

I think this issue is going to be quite challenging, but this moves us quite a bit forward toward a basis for consensus.
