### ISSUE TITLE
Contributor Orientation

### ISSUE THREAD

**Issue by elong0527** [pharmaR/riskmetric#58]
Shall we have a recorded orientation session to go through necessary information for people to contribute in one metric. (basically the nice Vignette @dgkf  wrote)

**Comment by dgkf** [comment]
Perhaps we can get the recording from the Validation Hub meeting where we did the introduction demo?

@andyofsmeg - Did we record the September Validation Hub session? If we did, is it possible to get a copy of the recording?

**Comment by dgkf** [comment]
Following up on this discussion. I reached out to Andy and he said that there's no recording available, so I think the best orientation might be the Getting Started vignette.
