### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by elong0527** [pharmaR/riskmetric#6]
### Proposal:

Mimic the idea of github mirror of all CRAN R packages (https://github.com/cran/emmeans)

Step 1: create read only repos.
Step 2: add CI yaml file using `devtools::use_travis`, `covr::use_coverage` etc
Step 3: read code coverage data from CI website (e.g. codecov.io)

**Comment by elong0527** [comment]
Challenge of the proposal:

1. some R package on CRAN did not have test folder but available in its github development repo (e.g. emmeans)

**Comment by kkmann** [comment]
Certainly a central one; my current proposal is based on covr (does that work for BC as well?) and really running the stuff locally (otherwise you'd have to trust the covr stats provider as well ;)).

covr provides super detailed analyses, we should probably discuss how to boil this down to one or two numbers (overall of course, do we need anything else?)

**Comment by elong0527** [comment]
Yes! I think it is the way to go. The overall code coverage may be sufficient to derive a risk score.

**Comment by dgkf** [comment]
@elong0527 - is the idea to make a 'read-only' mirror of packages with less standard test frameworks or under-covered test suites where additional tests are contributed? 

My personal preference would be to focus on evaluating packages as-is, and then be transparent about how the metrics are calculated to try to encourage more standard testing practices, and encourage contributions back to packages to shift them toward easier to automate testing suites with better coverage, although this leans on a more community-driven approach as opposed to a centrally governed approach. 

@kkmann - is this what you had in mind? I'm sort of confused about what the consensus in this thread is so far.

**Comment by elong0527** [comment]
I thought if the `test` folder is not in CRAN but in github repo, we will download it to local and put it in the package. This is not simple and may result in issue. 

I consider the start point is "read-only" mirror as you suggested as our target is to run the `covr` in a local environment.

**Comment by dgkf** [comment]
A few notes after our sprint meeting this morning:

- For our April milestone we're targeting having coverage implemented for `pkg_source` references only. Long term we might have to consider a way of coercing things like `pkg_remote` to a `pkg_source` upon downloading source code to run more rigorous assessments (#81)
- We decided to use `covr` as it is a widely used standard for package coverage today. @mpadge raised some very valid performance concerns in #94. We can consider something like "function coverage" via `utils::getParseData()` as a separate metric to "line coverage" or "expression coverage" as provided by `covr`. Long term it would be nice to be able to provide both such that someone could provide a subset via `assess(assessments = list(...))` to pick and choose a mode of assessment that suits their performance/rigor needs.
