### ISSUE TITLE
Metric for Source control Availability  (public)

### ISSUE THREAD

**Issue by elong0527** [pharmaR/riskmetric#63]
"The use of source control is good practice that facilitates development. In general it will not be possible to determine whether the maintainer is using a source code repository unless this is in the public domain." from https://github.com/pharmaR/pharmaR.github.io/blob/master/content/risk.md

The metric may translate to if there is a github repo for an R package.

**Comment by elong0527** [comment]
using the existing URL to identify the metric.

**Comment by dgkf** [comment]
Clarifying the objective here, we can look at both `BugReports` or `URL` in `DESCRIPTION` to see if either url points to a github.com or gitlab.com repository. We can consider other version control platforms if they're needed down the road.
