### ISSUE TITLE
Metric for Website availability 

### ISSUE THREAD

**Issue by elong0527** [pharmaR/riskmetric#64]
"It is good practice to maintain a website with further information about the package, contact details, and other supporting information." from https://github.com/pharmaR/pharmaR.github.io/blob/master/content/risk.md

it may translate if an R package uses pkgdown.yml

**Comment by elong0527** [comment]
action item:

* check if the website is actually enabled and host in a server. 
* is there other way to construct package website? (How did Bioconductor handle this?)

**Comment by mpadge** [comment]
For reference, we intend to adapt a number of aspects of [https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/criteria.md](https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/criteria.md), and in this regard their principles are particularly clear and useful.

**Comment by elong0527** [comment]
It might be challenge to guess a website if it is not described in the package.  How about we first collect URLs from the description file? 

For example, [ggplot2](https://cran.r-project.org/web/packages/ggplot2/index.html ) will extract two url:  

* http://ggplot2.tidyverse.org
* https://github.com/tidyverse/ggplot2

**Comment by dgkf** [comment]
@elong0527 - Yes, I think taking the URLs from DESCRIPTION should be the preferred mode of action. Even if other websites exist, I think it's safe to say that best practices would be to include these in the DESCRIPTION. 

Also, thanks @mpadge for that great resource. I've seen similar docs but this one is extremely comprehensive.
