### ISSUE TITLE
Risk score derivation

### ISSUE THREAD

**Issue by elong0527** [pharmaR/riskmetric#7]
Option 1:

Assuming risk score (rs) is 1-10 and 1 is the lowest risk score that cover the highest qualified R package on CRAN. 

Define a decision tree based rule for risk score. One R package may fit for multiple rule. The lowest score of all applied rule will be its final risk score. 

For example: 

Risk Score Rule 1: If 21CFR = "Y" then rs = 1
Risk Score Rule 2: if code_coverage > 80% and Vignettes = "Y" and News = “Y” and max( rs of all dependency packages) <= 3 then rs = 2
...

**Comment by dgkf** [comment]
_To capture the discussion from our call on Mar. 22nd, 2019_

The risk score derivation is considered a low priority until we can derive a representative set of metrics for a large cohort of packages. This will allow us to do some preliminary analysis of the distribution of metrics across packages and to start forming a notion of what metrics should be given more or less weight. 

This package may propose a suggested risk score function, but our goal isn't to define an industry standard. We may set forth a suggested function which can then be overwritten or replaced by a user to define risk by their own terms.

**Comment by kkmann** [comment]
@elong0527 are you okay with closing this for now - look's like its quite a long way from now and we ideally keep our issue board tidy ;)
