### ISSUE TITLE
update man entries for roxygen7.0

### ISSUE THREAD

**Issue by mpadge** [pharmaR/riskmetric#71]
`roxygen2` has been updated to [v7](https://cran.r-project.org/web/packages/roxygen2/index.html) which implements some formatting changes, and which changes almost all of your current `/man` entries. It'd be good for one of you to run `document()` on the package to update this, because otherwise anybody else wants to do a small PR that changes a single `/man` entry, and who has latest roxygen 7.0.0, will discover they've change *all* `/man` entries.

**Comment by dgkf** [comment]
Thanks for raising that @mpadge, we'll make that an immediate priority.

**Comment by elong0527** [comment]
@dgkf you probably already have this rerun in #73, I can double-check after we merge the current two pull requests.

**Comment by dgkf** [comment]
I don't think so. I haven't upgraded yet :$ 

We'll all have to upgrade to make sure we're not accidentally reverting this change, though so it will be good to get us all updated.

**Comment by elong0527** [comment]
got it, I have upgraded to 7.0.2. To reduce conflict we may handle it after the existing pull requests were merged.
