### ISSUE TITLE
New metrics from MangoDB

### ISSUE THREAD

**Issue by elong0527** [pharmaR/riskmetric#87]
add one new metric proposal from MangoDB

**Comment by dgkf** [comment]
Hey @elong0527 - can you clarify this a bit? Just one small correction, MangoDB is a database technology, but I think you're referring to Mango Solutions and the list of metrics that they outline in their [packageMetrics2](https://github.com/MangoTheCat/packageMetrics2) package.

The one that I mentioned on the call, for cyclomatic complexity has already been added in #82 

Were there others that you wanted to catalog here?

**Comment by elong0527** [comment]
I am closing this issue, as I notice you already create the issue.
