### ISSUE TITLE
Unit testing plan

### ISSUE THREAD

**Issue by elong0527** [pharmaR/riskmetric#89]
* list items to be tested. 

* class construction, 
* limitation of API for github (Does CI/CD server allow for this?)

**Comment by elimillera** [comment]
I was thinking about how to design a matrix structure for testing. That way we could test each one of the `pkg_ref` class types in the constructor and the `assess_*` functions.

Do we have any documentation about which assessments work for each `pkg_ref`? 

Regarding the API testing, in the past, I've just used environment variables or config files to store API information and test them locally. When travis or codecov goes to test the package they will just get skipped.

**Comment by mpadge** [comment]
I can recommend the rOpenSci suite of http mocking tools, described in [this work-in-progress book](https://books.ropensci.org/http-testing/) - makes it very easy to "record" http interactions for tests, and use only local playbacks.
