### ISSUE TITLE
BugReports error for pkg_install class object

### ISSUE THREAD

**Issue by dgkf** [pharmaR/riskmetric#92]
I stumbled upon this specifically with the `nlme` package, which I have installed in my local library.

```r
x <- pkg_ref("nlme")
stopifnot(inherits(x, "pkg_install"))  # check to confirm it's installed
x$bug_reports
```

Interestingly, `x$bug_reports_host` is somehow just set to `bugs`.

**Comment by emilliman5** [comment]
This behavior is because bug reports for nlme (and other official R packages) are hosted on a subdomain of the r-project.org site, i.e. https://bugs.r-project.org. Instead of `extract_host()` we could use `domain()`

**Comment by elong0527** [comment]
Agree to use  `domain` 

add testing cases to ensure the change works for `github` and `gitlab`
