### ISSUE TITLE
Spec out metrics for web app

### ISSUE THREAD

**Issue by dgkf** [pharmaR/riskmetric#94]
@elong0527 @andyofsmeg @emdserono 

The broader R Validation Hub will be planning to deliver a web app as a standalone tool for organization risk assessment report generation and they've asked that we give some guidance on what can be reliably built upon from `riskmetric`.

There are a few things we need to consider to help that team scope out their work.

### Metrics

So far we have these metrics completed or partially completed:
- downloads in last year (integer)
- exported objects with documentation (percentage)
- package has news (logical)
- package has vignettes (logical)
- status of last 30 reported bugs (percentage)
- license (NA - up to organization)
- news is current (logical)

We should scope out which metrics additionally need to be completed. At a minimum, we need to provide the expected output format of the metric assessment. Just to list a few, I would suggest the following as targets in increasing difficulty:

|Status|Metric|Notes|
|:-:|---|---|
|✅|has website|`$pkg_websites` implemented, still need `assess_has_website_url`, `score.pkg_metric_has_website_url`|
|✅|has BugReports| `$bug_reports_url` implemented, need `assess_has_bug_reports`, `score.pkg_metric_has_bug_reports` (#100)|
|✅|has a maintainer|`$maintainer` implemented, need `assess_has_maintainer`, `score.pkg_metric_has_maintainer` (#55)|
|✅|source code is public|`$source_control_url` implemented (but currently not visible due to bug addressed in #117), need `assess_has_source_control_url`, `score.pkg_metric_has_source_control_url` (#63)|
|❓|time since first release|`$archive_release_dates` implemented only for `cran_remote`s, scoring under consideration (#65, #85)|
|❓|time since version release|`$release_date` implemented, scoring under consideration (#65, #85)
| ✅|test coverage| finished for `pkg_install` only, `pkg_source` under consideration (#6)|

### Assessment Caching 

One thing that came up is the possibility of storing metric assessment scores as a data intermediate encompassing the time that the assessment occurred, the package metadata, assessed information and scored metrics. 

This might be deemed out of scope in the first pass, but if risk assessment times grow too long for an interactive app we may have to think about some ways to do caching. 

The easiest solution would be to save out the results dataset as a `.Rds`, but if generalizability is needed we might have to consider a machine readable intermediate. Given the focus on atomic intermediate assessment datastructures, I don't think this should be too difficult, but does pose additional development work.

**Comment by elong0527** [comment]
I think the first four shall be easy to handle. 
 
I hope to understand more how to implement test coverage. If this is for Shiny app, we might need to enhance the user experience to reduce response time. Running `covr` on the server will take non-trivial time.

**Comment by andyofsmeg** [comment]
I am not so concerned about the lag time as it will be one-time only to collect the information and store it in a DB.  That said, if it could somehow run in the background that would be great but not easy with R!

**Comment by dgkf** [comment]
> @elong0527 [#94](https://github.com/pharmaR/riskmetric/issues/94#issuecomment-598468673)
> Running `covr` on the server will take non-trivial time.

Yeah - I think test coverage would be the breaking point between a  reasonable and uncomfortable delay after producing a report on-the-fly.  

> @andyofsmeg [#94](https://github.com/pharmaR/riskmetric/issues/94#issuecomment-598675788)
>  it will be one-time only to collect the information and store it in a DB

@andyofsmeg - How would you feel about the DB just being an R data object (`.Rds`). I think that this would be by far the simplest way to store out some metrics data. It definitely couples the two projects a bit more tightly, which I usually try to avoid, but my priority here is getting a functional app up and running and to avoid introducing too many new features to `riskmetric` (aka `pakmet`? 🤐) for the sake of accommodating the shiny app.

**Comment by andyofsmeg** [comment]
> @andyofsmeg - How would you feel about the DB just being an R data object (`.Rds`). I think that this would be by far the simplest way to store out some metrics data. It definitely couples the two projects a bit more tightly, which I usually try to avoid, but my priority here is getting a functional app up and running and to avoid introducing too many new features to `riskmetric` (aka `pakmet`? 🤐) for the sake of accommodating the shiny app.

I'll ask the team - if nothing else that should be find for them to pick up and work with, certainly better than a CSV.

**Comment by andyofsmeg** [comment]
Any further thoughts on the metrics themselves?  Are there key ones that you think we really need in a first version of the app / a CRAN release of riskmetric?

**Comment by dgkf** [comment]
Let's stick with these 5. I'm not seeing any further concerns being raised here. 

I think that running unit test coverage is probably the biggest one that I'd like to see prior to a CRAN release - that's really the baseline that I'd imagine most would expect when they think of software rigor.

**Comment by mpadge** [comment]
The efficient generation of coverage estimates is something we're all going to have to deal with at some stage. The potential good news is that we've done some playing around in this area, and are hoping to be able to offer help sometime in the not too distant future. There are different ways of estimating coverage, and `covr` uses arguably the most comprehensive approach of recursively tracing all function (within function, within function ...) calls. Comprehensive here also implies notable compromises in efficiency. Part of what we may well end up developing for our project is a simpler yet hopefully much more efficient approach to estimating coverage, based on the `utils::getParseData()` function. 

`covr` actually traces the execution of all calls along each line of code, and so generates an accurate line-based metric. Using `getParseData()` enables function-based coverage estimates, often with little or no information on paths actually traced within functions, but for that price you get virtually instantaneous results. In short: This is a problem that the collective "*we*" will hopefully find a solution for at some stage, and so don't have to worry too much about for the moment.

(Cross-link to #6, where this comment maybe more rightly should reside.)

**Comment by andyofsmeg** [comment]
Thanks everyone.  I'll take this back and replay the final list of agreed metrics with you.

**Comment by andyofsmeg** [comment]
Following a cross check, I also had "time since _version_ release (difftime)" in addition to _first_ release.  I would have thought that would be fairly straightforward if you already have time since first release.
