### ISSUE TITLE
Mitigating number of Imports package dependencies

### ISSUE THREAD

**Issue by dgkf** [pharmaR/riskmetric#99]
One of the looming challenges with this package is the potential for the dependency footprint to really snowball into a pretty hefty cohort.

There are a number of dependencies that are nice to have throughout the package. Relatively lightweight, but convenient packages like `rvest` are good for making a number of remote operations easier. Having `tibble` and `pillar` make for a much nicer console interface when assessing multiple packages.

However, we also have a large number of metric specific packages and I expect this number to grow as we start pulling in more computationally intensive metrics. This includes packages like `covr`, `testthat`, `cyclocomp`. 

Perhaps we could think of a way of tagging assess functions with their package dependencies such that we can build a small onLoad dialog about what assess functions will be ignored until their additional Suggested package dependencies are installed? This would let us focus on a small set of minimal dependencies for general behaviors while still allowing for more complex functionality through package extensions.

**Comment by elong0527** [comment]
Based on the master branch, I am using the `itdepends` package to get this report. The package seems not be able to capture function that uses :: namespace.  So I also add the one find in files.

```
memories::memoise
remotes::cran_remote
remotes::github_remote
rvest::html_nodes
rvest::html_attr
%>%
stringer::str_extract
httr::content
tibble::as_tibble
janitor::clean_names 
```


```
> x <- itdepends::dep_usage_pkg("riskmetric") 
> x %>% subset(! pkg %in% c("base", "riskmetric", "tools", "utils")) %>% arrange(pkg, fun) %>% unique() %>% data.frame()
        pkg                     fun
1      covr        coverage_to_list
2      covr        package_coverage
3      covr          tally_coverage
4  cranlogs          cran_downloads
5    crayon                    bold
6      curl                    curl
7      curl                nslookup
8     dplyr               as_tibble
9     dplyr                  tibble
10    fansi             strwrap_ctl
11 jsonlite              parse_json
12   pillar new_pillar_shaft_simple
13   pillar            pillar_shaft
14   pillar                style_na
15   pillar            style_subtle
16   tibble               as_tibble
17 urltools                  domain
18 urltools            host_extract
19 urltools              url_encode
20    vctrs             new_list_of
21     xml2               read_html
22     xml2            url_absolute
23     xml2                xml_attr
24     xml2               xml_attrs
25     xml2            xml_find_all
```

**Comment by elong0527** [comment]
I am thinking of replacing functions as the first step. How would you think @dgkf ?  

```
rvest
dplyr
stringr
tibble
vctrs
```

**Comment by dgkf** [comment]
Looking through our dependencies, I think we can really cut back on which we need to import. We can move a few others to "Enhances" for things like intensive coverage analysis, service API requests and tidyverse compatibility. Otherwise we use a fairly small set of features from most other packages and often for legacy code that isn't needed any longer. 

# Keep as "Imports"

#### Basics

```
utils
tools
xml2
httr
curl
urltools
memoise
```

#### Package Repository Interfaces

```
BiocManager
cranlogs
```

# Move to "Enhances"

I think we can probably write a small helper function to flag certain functions with additional package requirements and throw an error if those packages can't be loaded. We might want to include a helper function to install all "Enhances" packages.

#### Unit Testing

```
covr # considering keeping this in imports; not too heavy on dependencies (+6)
```

#### GitHub Web-request related

```
gh
jsonlite # only used for parsing GitHub bug reports API response
```

#### Tidyverse interop

```
tibble
vctrs
pillar
```

# Remove

There are a good number of packages that are used only for very few functions. I think we can scrap the developer hints functionality for now - maybe we can circle back to that after we have good metric coverage. A lot of the tidyverse helper packages can probably be removed in favor of lighter weight alternatives. 

#### Only used for developer hints 
_pilot functionality to provide tips for improving package quality_

```
fansi
crayon
```

#### Currently Unused

```
remotes
janitor
magrittr
stringr
rvest
dplyr # can replace re-export with only tibble::tibble
```

# Running some stats

Just for fun I tried to be a bit more thoughtful about where this line should be. I wrote up some code to look at how many dependencies are incurred using each set of packages:

```r
> library(miniCRAN)
> imports <- c("utils", "tools", "xml2", "httr", "curl", "urltools", "memoise", "BiocManager", "cranlogs")
> enhances <- c("covr", "jsonlite", "gh", "tibble", "vctrs", "pillar")
> remove <- c("remotes", "janitor", "magrittr", "stringr", "rvest", "dplyr")
```
```r
> length(pkgDep(imports, suggests = FALSE))
# [1] 16
> plot(makeDepGraph(imports, suggests = FALSE), main = "imports")
```
![image](https://user-images.githubusercontent.com/18220321/81025934-49242700-8e2d-11ea-8a2e-79ca2bc11a6a.png)
```r
> length(pkgDep(c(imports, enhances), suggests = FALSE))
# [1] 37
> plot(makeDepGraph(c(imports, enhances), suggests = FALSE), main = "imports + enhances")
```
![image](https://user-images.githubusercontent.com/18220321/81025971-740e7b00-8e2d-11ea-9967-20a77eb016b2.png)
```r
> length(pkgDep(c(imports, enhances, remove), suggests = FALSE))
# [1] 52
> plot(makeDepGraph(c(imports, enhances, remove), suggests = FALSE), main = "imports + enhances + removed")
```
![image](https://user-images.githubusercontent.com/18220321/81026003-88eb0e80-8e2d-11ea-9141-9e7cae160b9c.png)

**Comment by elong0527** [comment]
Priority 

- [ ] remove unused packages

remotes
janitor
magrittr
stringr
rvest
dplyr

- [ ]  example of enhancement 

covr

**Comment by mpadge** [comment]
I just discovered the cool [`pkgndep` package](https://github.com/jokergoo/pkgndep):
``` r
library(riskmetric)
library(pkgndep)
x <- pkgndep ("riskmetric")
#> ========== checking riskmetric ==========
#> Loading BiocManager to a new R session... 10 namespaces loaded.
#> Loading utils to a new R session... 9 namespaces loaded.
#> Loading tools to a new R session... 9 namespaces loaded.
#> Loading xml2 to a new R session... 10 namespaces loaded.
#> Loading httr to a new R session... 11 namespaces loaded.
#> Loading curl to a new R session... 10 namespaces loaded.
#> Loading jsonlite to a new R session... 10 namespaces loaded.
#> Loading remotes to a new R session... 10 namespaces loaded.
#> Loading gh to a new R session... 18 namespaces loaded.
#> Loading urltools to a new R session... 12 namespaces loaded.
#> Loading magrittr to a new R session... 10 namespaces loaded.
#> Loading stringr to a new R session... 12 namespaces loaded.
#> Loading dplyr to a new R session... 24 namespaces loaded.
#> Loading tibble to a new R session... 18 namespaces loaded.
#> Loading vctrs to a new R session... 11 namespaces loaded.
#> Loading pillar to a new R session... 12 namespaces loaded.
#> Loading crayon to a new R session... 10 namespaces loaded.
#> Loading fansi to a new R session... 10 namespaces loaded.
#> Loading covr to a new R session... 12 namespaces loaded.
#> Loading rvest to a new R session... 14 namespaces loaded.
#> Loading memoise to a new R session... 11 namespaces loaded.
#> Loading janitor to a new R session... 30 namespaces loaded.
#> Loading cranlogs to a new R session... 13 namespaces loaded.
#> Loading knitr to a new R session... 11 namespaces loaded.
#> Loading rmarkdown to a new R session... 17 namespaces loaded.
#> Loading testthat to a new R session... 13 namespaces loaded.
apply (x$mat, 1, function (i) length (which (!is.na (i)))) %>%
    sort (decreasing = TRUE)
#>     janitor       dplyr          gh      tibble   rmarkdown       rvest 
#>          30          24          18          18          17          14 
#>    cranlogs    testthat    urltools     stringr      pillar        covr 
#>          13          13          12          12          12          12 
#>        httr       vctrs     memoise       knitr BiocManager        xml2 
#>          11          11          11          11          10          10 
#>        curl    jsonlite     remotes    magrittr      crayon       fansi 
#>          10          10          10          10          10          10 
#>       utils       tools 
#>           9           9
```

<sup>Created on 2020-05-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So `janitor` and `dplyr` are the killers there. Useful huh?

**Comment by dgkf** [comment]
Very helpful! Thanks @mpadge. That's good news. I think that we've done a good job of preempting the removal of `dplyr` and minimizing our usage as much as possible and `janitor` is vestigial from some really early contributions when we were still experimenting with the general design. I think we have some easy wins here!

**Comment by elong0527** [comment]
Will remove 
Please help me check whether we can remove `rvest` package dependency. 

Below is a list of functions we used  
```
rvest::html_table
rvest::html_node
rvest::html_text
```

There are another four packages in the enhanced category. I will need help to understand how to achieve that.

```
    gh,
    jsonlite,
    vctrs,
    pillar,
```

**Comment by elong0527** [comment]
@dgkf , could you provide reference how to handle packages in the enhanced category?
